FROM php:8.2-fpm-alpine

# Below is for caching to be anabled during production
# RUN docker-php-ext-install opcache
# COPY php/production/opcache.ini /usr/local/etc/php/conf.d/opcache.ini

# Below is enabled during production and requires disabling of the volumes in the .yml file
# COPY ./data/ /var/www/html/